name: Hello Input

on:
  workflow_dispatch:
    inputs:
      InputParameter:
        description: "Name to print"
        required: true
        default: "World"
      Branch:
        description: "Branch name"
        required: true
        default: "main"

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: |
          echo "Hello from ${{ github.event.inputs.InputParameter }}"
          echo "branch is ${{ github.event.inputs.Branch }}"
