name: Hello World

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '10 12 * * *'

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World!"